Feature: allow to select only .zip files
SergioGlorias/Discloud-on-Commit pull request #2
Opened 2022-12-14 21:03 UTC by DiogoMarques2003

2022-12-14 21:28 UTC, SergioGlorias requested changes

2022-12-14 21:28 UTC, SergioGlorias commented on index.html
> +                  accept=".zip"
tem um porem
o commit aceita coisa até sem ser com zip

2022-12-15 20:01 UTC, DiogoMarques2003 commented on index.html
> +                  accept=".zip"
So adicionar o resto das extenções ai, seprando por `,`

2022-12-15 20:26 UTC, SergioGlorias commented on index.html
> +                  accept=".zip"
quando não é zip aceito qualquer coisa

2022-12-15 20:26 UTC, SergioGlorias commented on index.html
> +                  accept=".zip"
para comitar na raiz sim

2022-12-26 17:34 UTC, closed without merging